### ISSUE TITLE
ERROR: MethodError: no method matching spdiagm(::SparseVector{Int64,Int64})

### ISSUE THREAD

**Issue by liwen-alt** [arbenson/HigherOrderClustering.jl#3]
![image](https://user-images.githubusercontent.com/63285313/85018065-206aad80-b19f-11ea-98b9-7c078b056b6a.png)
![image](https://user-images.githubusercontent.com/63285313/85018104-35dfd780-b19f-11ea-8093-503e88b2253a.png)

**Comment by arbenson** [comment]
This package is now updated for Julia 1.4.
