### ISSUE TITLE
I used Jupyter run HigherOrderClustering,it still can't install it

### ISSUE THREAD

**Issue by liwen-alt** [arbenson/HigherOrderClustering.jl#4]
![image](https://user-images.githubusercontent.com/63285313/85020511-07fc9200-b1a3-11ea-9363-467b5c6d16e5.png)

**Comment by liwen-alt** [comment]
could tell me how to compute higher_order_cluster coefficient with julia?

**Comment by arbenson** [comment]
Please see the README. The package was just updated.
